### ISSUE TITLE
Redesign Projects Page Top Header

### ISSUE THREAD

**Issue by mraguso2** [mraguso2/gatsby-mr-site#3]
Looking to redesign the project page header https://www.mikeraguso.com/projects. 
Initial style changes can include:

- making the current image background to transparent, 
- removing the background gradient, 
- editing the border box around the image, 
- border-radius to be more consistent with other objects 
- and redesigning the page title "Projects" 

I will setup a new branch for this style change that should be used for PR please (Rewrite_ProjectHeader)

**Comment by epolis185** [comment]
Hi, I'd like to give this a shot

**Comment by epolis185** [comment]
PR: https://github.com/mraguso2/gatsby-mr-site/pull/4
